name: Java CI with Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          node-version: '20'

      - name: Print Java Version
        run: java -version

      - name: Print Gradle Version
        run: gradle --version

      - name: Build with Gradle
        run: gradle build -s -i

      - name: Run tests
        run: gradle test -s -i
